spring:
  application:
    name: explanation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/anomalydb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: explanation-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.siqiuma.explanation_service.model
        spring.json.value.default.type: com.siqiuma.explanation_service.model.ExplanationRequestEvent
        spring.json.use.type.headers: false
llm:
  provider: openai
  api-key:
  endpoint: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini
  timeout-ms: 5000

server:
  port: 8082